import type { DisputeSummary, FeedbackSummary, RTSSummary } from '@/types'

export function generateMarkdownSummary(summary: DisputeSummary): string {
  const lines: string[] = []

  lines.push(`# DSP Concession Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total Concessions | ${summary.totalConcessions} |`)
  lines.push(`| Impacts DSB | ${summary.impactsDSBCount} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  const autoRate = summary.totalConcessions > 0
    ? ((summary.autoDisputedCount / summary.totalConcessions) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (2+ Concessions)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | Concession Count |`)
    lines.push(`|-------------|-----------|------------------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.concessionCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 2+ concessions may require coaching or additional oversight.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 2+ concessions this period.`)
    lines.push('')
  }

  lines.push(`## Dispute Reason Summary`)
  lines.push('')
  const sortedReasons = Object.entries(summary.reasonBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedReasons.length > 0) {
    lines.push(`| Reason | Count |`)
    lines.push(`|--------|-------|`)
    for (const [reason, count] of sortedReasons) {
      lines.push(`| ${reason} | ${count} |`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}

export function generateFeedbackMarkdownSummary(summary: FeedbackSummary): string {
  const lines: string[] = []

  lines.push(`# Customer Feedback Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total Feedback Items | ${summary.totalFeedback} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  const autoRate = summary.totalFeedback > 0
    ? ((summary.autoDisputedCount / summary.totalFeedback) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  lines.push(`## Priority Tier Breakdown`)
  lines.push('')
  lines.push(`| Tier | Description | Count |`)
  lines.push(`|------|-------------|-------|`)
  lines.push(`| Tier 1 | Wrong Address / Never Received | ${summary.tierCounts.tier1} |`)
  lines.push(`| Tier 2 | Didn't Follow Instructions | ${summary.tierCounts.tier2} |`)
  lines.push(`| Tier 3 | Manual Review (Mishandled/Unprofessional/Wrong Item) | ${summary.tierCounts.tier3} |`)
  lines.push('')

  lines.push(`## Feedback Type Breakdown`)
  lines.push('')
  const sortedTypes = Object.entries(summary.feedbackTypeBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedTypes.length > 0) {
    lines.push(`| Feedback Type | Count |`)
    lines.push(`|---------------|-------|`)
    for (const [type, count] of sortedTypes) {
      lines.push(`| ${type} | ${count} |`)
    }
    lines.push('')
  }

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ Feedback Items)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | Feedback Count |`)
    lines.push(`|-------------|-----------|----------------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.feedbackCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ negative feedback items may require coaching.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ feedback items this period.`)
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}

export function generateRTSMarkdownSummary(summary: RTSSummary): string {
  const lines: string[] = []

  lines.push(`# DCR/RTS Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  // MARCH 2026 UPDATE WARNING
  lines.push(`> ⚠️ **IMPORTANT: March 11, 2026 Amazon Update**`)
  lines.push(`> `)
  lines.push(`> Amazon now **AUTO-EXEMPTS** most "Package Not on Van" cases:`)
  lines.push(`> - Packages rerouted while driver on route (OODT, RTS-Other)`)
  lines.push(`> - "Object Missing" packages later delivered by another DA`)
  lines.push(`> `)
  lines.push(`> **You no longer need to dispute these cases** - Amazon handles them automatically.`)
  lines.push(`> Focus disputes on rare cases: packages delivered same day but incorrectly marked RTS.`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total RTS | ${summary.totalRTS} |`)
  lines.push(`| Impacts DCR | ${summary.impactsDCRCount} |`)
  lines.push(`| ✓ Auto-Exempted by Amazon | ${summary.autoExemptedByAmazonCount || 0} |`)
  lines.push(`| Already Exempted (other) | ${summary.alreadyExemptedCount} |`)
  lines.push(`| Worth Disputing | ${summary.highConfidenceCount} |`)
  lines.push(`| Not Worth Disputing | ${summary.lowConfidenceCount} |`)
  lines.push('')

  // Show savings
  const autoExempted = summary.autoExemptedByAmazonCount || 0
  if (autoExempted > 0) {
    lines.push(`### Time Saved`)
    lines.push(``)
    lines.push(`**${autoExempted} disputes** you don't need to file - Amazon auto-exempts them.`)
    lines.push('')
  }

  lines.push(`## Dispute Breakdown`)
  lines.push('')
  lines.push(`### ✓ Auto-Exempted by Amazon (NO DISPUTE NEEDED)`)
  lines.push('')
  lines.push(`These RTS codes are now automatically exempted as of March 11, 2026:`)
  lines.push(`- OBJECT MISSING, PACKAGE NOT FOUND, NOT IN VAN, MISROUTE`)
  lines.push(`- OODT, RTS-OTHER (packages rerouted while driver on route)`)
  lines.push('')

  const sortedHighConfidence = Object.entries(summary.highConfidenceBreakdown || {})
    .sort(([, a], [, b]) => b - a)

  if (sortedHighConfidence.length > 0) {
    lines.push(`| RTS Code | Count |`)
    lines.push(`|----------|-------|`)
    for (const [code, count] of sortedHighConfidence) {
      lines.push(`| ${code} | ${count} |`)
    }
    lines.push('')
  } else {
    lines.push(`*No high-confidence cases found in this file.*`)
    lines.push('')
  }

  lines.push(`### Low-Confidence Disputes (DO NOT SUBMIT)`)
  lines.push('')
  lines.push(`These are valid RTS scenarios from Amazon's perspective. Disputing these has a <1% approval rate:`)
  lines.push(`- Business Closed - legitimate if business was actually closed`)
  lines.push(`- Locker Full/Unavailable - legitimate logistics constraint`)
  lines.push(`- OODT - package returned within policy guidelines`)
  lines.push(`- Customer Unavailable/Refused - legitimate delivery outcome`)
  lines.push('')

  const sortedLowConfidence = Object.entries(summary.lowConfidenceBreakdown || {})
    .sort(([, a], [, b]) => b - a)

  if (sortedLowConfidence.length > 0) {
    lines.push(`| RTS Code | Count | Why Rejected |`)
    lines.push(`|----------|-------|--------------|`)
    for (const [code, count] of sortedLowConfidence) {
      const reason = getLowConfidenceReason(code)
      lines.push(`| ${code} | ${count} | ${reason} |`)
    }
    lines.push('')
  }

  lines.push(`## All RTS Codes`)
  lines.push('')
  const sortedCodes = Object.entries(summary.rtsCodeBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedCodes.length > 0) {
    lines.push(`| RTS Code | Count |`)
    lines.push(`|----------|-------|`)
    for (const [code, count] of sortedCodes) {
      lines.push(`| ${code} | ${count} |`)
    }
    lines.push('')
  }

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ RTS)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | RTS Count |`)
    lines.push(`|-------------|-----------|-----------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.rtsCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ RTS may need route optimization coaching.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ RTS this period.`)
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}

// Helper function to get rejection reason for low-confidence codes
function getLowConfidenceReason(code: string): string {
  const upperCode = code.toUpperCase()
  if (upperCode.includes('BUSINESS CLOSED')) return 'Valid RTS - business hours issue'
  if (upperCode.includes('LOCKER')) return 'Valid RTS - capacity issue'
  if (upperCode.includes('OODT') || upperCode.includes('TIME')) return 'Valid RTS - delivery window'
  if (upperCode.includes('CUSTOMER') || upperCode.includes('REFUSED')) return 'Valid RTS - customer decision'
  if (upperCode.includes('ACCESS') || upperCode.includes('GATE')) return 'Valid RTS - access restriction'
  if (upperCode.includes('WEATHER') || upperCode.includes('EMERGENCY')) return 'Valid RTS - safety issue'
  return 'Low historical approval rate'
}
