import type { DisputeSummary } from '@/types'

export function generateMarkdownSummary(summary: DisputeSummary): string {
  const lines: string[] = []

  // Header
  lines.push(`# DSP Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  // Overview Statistics
  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total Concessions | ${summary.totalConcessions} |`)
  lines.push(`| Impacts DSB | ${summary.impactsDSBCount} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  // Auto-dispute rate
  const autoRate = summary.totalConcessions > 0
    ? ((summary.autoDisputedCount / summary.totalConcessions) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  // Priority Tier Breakdown
  lines.push(`## Priority Tier Breakdown`)
  lines.push('')
  lines.push(`| Tier | Description | Count |`)
  lines.push(`|------|-------------|-------|`)
  lines.push(`| Tier 1 | Impacts DSB (Highest Priority) | ${summary.tierCounts.tier1} |`)
  lines.push(`| Tier 2 | Within Geo + Has POD | ${summary.tierCounts.tier2} |`)
  lines.push(`| Tier 3 | Attended Delivery | ${summary.tierCounts.tier3} |`)
  lines.push(`| Tier 4 | Manual Review Required | ${summary.tierCounts.tier4} |`)
  lines.push('')

  // Repeat Drivers
  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ Concessions)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | Concession Count |`)
    lines.push(`|-------------|-----------|------------------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.concessionCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ concessions may require coaching or additional oversight.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ concessions this period.`)
    lines.push('')
  }

  // Reason Breakdown
  lines.push(`## Dispute Reason Summary`)
  lines.push('')
  const sortedReasons = Object.entries(summary.reasonBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedReasons.length > 0) {
    lines.push(`| Reason | Count |`)
    lines.push(`|--------|-------|`)
    for (const [reason, count] of sortedReasons) {
      lines.push(`| ${reason} | ${count} |`)
    }
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}
