import type { DisputeSummary, FeedbackSummary, RTSSummary } from '@/types'

export function generateMarkdownSummary(summary: DisputeSummary): string {
  const lines: string[] = []

  lines.push(`# DSP Concession Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total Concessions | ${summary.totalConcessions} |`)
  lines.push(`| Impacts DSB | ${summary.impactsDSBCount} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  const autoRate = summary.totalConcessions > 0
    ? ((summary.autoDisputedCount / summary.totalConcessions) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  lines.push(`## Priority Tier Breakdown`)
  lines.push('')
  lines.push(`| Tier | Description | Count |`)
  lines.push(`|------|-------------|-------|`)
  lines.push(`| Tier 1 | Impacts DSB (Highest Priority) | ${summary.tierCounts.tier1} |`)
  lines.push(`| Tier 2 | Within Geo + Has POD | ${summary.tierCounts.tier2} |`)
  lines.push(`| Tier 3 | Attended Delivery | ${summary.tierCounts.tier3} |`)
  lines.push(`| Tier 4 | Manual Review Required | ${summary.tierCounts.tier4} |`)
  lines.push('')

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ Concessions)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | Concession Count |`)
    lines.push(`|-------------|-----------|------------------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.concessionCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ concessions may require coaching or additional oversight.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ concessions this period.`)
    lines.push('')
  }

  lines.push(`## Dispute Reason Summary`)
  lines.push('')
  const sortedReasons = Object.entries(summary.reasonBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedReasons.length > 0) {
    lines.push(`| Reason | Count |`)
    lines.push(`|--------|-------|`)
    for (const [reason, count] of sortedReasons) {
      lines.push(`| ${reason} | ${count} |`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}

export function generateFeedbackMarkdownSummary(summary: FeedbackSummary): string {
  const lines: string[] = []

  lines.push(`# Customer Feedback Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total Feedback Items | ${summary.totalFeedback} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  const autoRate = summary.totalFeedback > 0
    ? ((summary.autoDisputedCount / summary.totalFeedback) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  lines.push(`## Priority Tier Breakdown`)
  lines.push('')
  lines.push(`| Tier | Description | Count |`)
  lines.push(`|------|-------------|-------|`)
  lines.push(`| Tier 1 | Wrong Address / Never Received | ${summary.tierCounts.tier1} |`)
  lines.push(`| Tier 2 | Didn't Follow Instructions | ${summary.tierCounts.tier2} |`)
  lines.push(`| Tier 3 | Manual Review (Mishandled/Unprofessional/Wrong Item) | ${summary.tierCounts.tier3} |`)
  lines.push('')

  lines.push(`## Feedback Type Breakdown`)
  lines.push('')
  const sortedTypes = Object.entries(summary.feedbackTypeBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedTypes.length > 0) {
    lines.push(`| Feedback Type | Count |`)
    lines.push(`|---------------|-------|`)
    for (const [type, count] of sortedTypes) {
      lines.push(`| ${type} | ${count} |`)
    }
    lines.push('')
  }

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ Feedback Items)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | Feedback Count |`)
    lines.push(`|-------------|-----------|----------------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.feedbackCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ negative feedback items may require coaching.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ feedback items this period.`)
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}

export function generateRTSMarkdownSummary(summary: RTSSummary): string {
  const lines: string[] = []

  lines.push(`# DCR/RTS Dispute Summary`)
  lines.push(`**Station:** ${summary.station} | **Week:** ${summary.week}`)
  lines.push('')

  lines.push(`## Overview`)
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total RTS | ${summary.totalRTS} |`)
  lines.push(`| Impacts DCR | ${summary.impactsDCRCount} |`)
  lines.push(`| Already Exempted | ${summary.alreadyExemptedCount} |`)
  lines.push(`| Needs Dispute | ${summary.autoDisputedCount + summary.manualReviewCount} |`)
  lines.push(`| Auto-Disputed | ${summary.autoDisputedCount} |`)
  lines.push(`| Manual Review Required | ${summary.manualReviewCount} |`)
  lines.push('')

  const disputeableCount = summary.autoDisputedCount + summary.manualReviewCount
  const autoRate = disputeableCount > 0
    ? ((summary.autoDisputedCount / disputeableCount) * 100).toFixed(1)
    : '0.0'
  lines.push(`**Auto-Dispute Rate:** ${autoRate}%`)
  lines.push('')

  lines.push(`## Priority Tier Breakdown`)
  lines.push('')
  lines.push(`| Tier | Description | Count |`)
  lines.push(`|------|-------------|-------|`)
  lines.push(`| Tier 1 | Business Closed / No Locker | ${summary.tierCounts.tier1} |`)
  lines.push(`| Tier 2 | Out of Delivery Time | ${summary.tierCounts.tier2} |`)
  lines.push(`| Tier 3 | Manual Review Required | ${summary.tierCounts.tier3} |`)
  lines.push('')

  lines.push(`## RTS Code Breakdown`)
  lines.push('')
  const sortedCodes = Object.entries(summary.rtsCodeBreakdown)
    .sort(([, a], [, b]) => b - a)

  if (sortedCodes.length > 0) {
    lines.push(`| RTS Code | Count |`)
    lines.push(`|----------|-------|`)
    for (const [code, count] of sortedCodes) {
      lines.push(`| ${code} | ${count} |`)
    }
    lines.push('')
  }

  if (summary.repeatDrivers.length > 0) {
    lines.push(`## Repeat Drivers (3+ RTS)`)
    lines.push('')
    lines.push(`| Driver Name | Driver ID | RTS Count |`)
    lines.push(`|-------------|-----------|-----------|`)
    for (const driver of summary.repeatDrivers) {
      lines.push(`| ${driver.name} | ${driver.driverId} | ${driver.rtsCount} |`)
    }
    lines.push('')
    lines.push(`> **Note:** Drivers with 3+ RTS may need route optimization coaching.`)
    lines.push('')
  } else {
    lines.push(`## Repeat Drivers`)
    lines.push('')
    lines.push(`No drivers with 3+ RTS this period.`)
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by DSP Dispute Automation Tool on ${new Date().toISOString().split('T')[0]}*`)

  return lines.join('\n')
}
